### ISSUE TITLE
Demo stops working

### ISSUE THREAD

**Issue by pmoscicki** [iendeavor/vue-next-select#1]

**Comment by iendeavor** [comment]
@pmoscicki Thanks for issue, it works now.

**Comment by bci24** [comment]
the demo still not works. 
It freeze on google chrome 87 (ubuntu 20.04)

**Comment by iendeavor** [comment]
@bci24  Fixed (v0.1.2)

**Comment by paulinechi** [comment]
Demo still not working, https://iendeavor.github.io/vue-next-select/examples.html shows ```Error fetching sandbox.```
 for chrome.
