### ISSUE TITLE
select item with keyboard in searchable

### ISSUE THREAD

**Issue by tofulm** [iendeavor/vue-next-select#121]
In select with search : https://iendeavor.github.io/vue-next-select/#select-with-search-header
is it possible to select an item with the keyboard keys ?

**Comment by iendeavor** [comment]
Done, please try v1.3.0. 😄

https://github.com/iendeavor/vue-next-select/commit/a50dccf48a38d899ac49df73d7f480c84440671b

**Comment by tofulm** [comment]
I tested https://github.com/iendeavor/vue-next-select/commit/a50dccf48a38d899ac49df73d7f480c84440671b
When I click to open : select option, 
highlight does not work correctly : 
 
![menu](https://user-images.githubusercontent.com/2989137/111696720-eebd6a80-8834-11eb-92c5-e41bc716bcaf.gif)

**Comment by iendeavor** [comment]
Yes, there has some bug to fix, I will fix it in one day.

Thank you for your fallback. 😃

**Comment by iendeavor** [comment]
@tofulm Please try it (v1.3.2) again. It should works now. :smile:

**Comment by tofulm** [comment]
Thanks !!!!
it works very well
