### ISSUE TITLE
Error: Module parse failed

### ISSUE THREAD

**Issue by dragoonzx** [iendeavor/vue-next-select#137]
**Describe the bug**
./node_modules/vue-next-select/dist/vue-next-select.es.prod.js 1:5557
Module parse failed: Unexpected token

**Comment by iendeavor** [comment]
Thank you for report this issue, could you provide more details like environments or reproduce steps?

**Comment by dragoonzx** [comment]
Project was generated with vue-cli, it may be the problem?

**Comment by iendeavor** [comment]
Thank you again, no, It is because I didn't downgrade syntax. I will fix it.

**Comment by iendeavor** [comment]
@dragoonzx please try v2.0.1 again 😄 .
