### ISSUE TITLE
Custom Scrollbar

### ISSUE THREAD

**Issue by MatthijsBe** [iendeavor/vue-next-select#149]
Hi I was wondering if a "custom Scrollbar" is on the roadmap?

**Comment by iendeavor** [comment]
Do you mean the style of the scrollbar?

**Comment by MatthijsBe** [comment]
@iendeavor Yes correctly, and is there a best practice to apply my own style? Or just simply override using the existing selectors?

**Comment by iendeavor** [comment]
Just override it.

We aim to provide functionality for select use cases, not for style, we are only applying some basic styles for now.

**Comment by iendeavor** [comment]
Thanks for your question, if you need other questions or suggestions, please feel free to open issues 😄 .
