### ISSUE TITLE
CSS style adoption of Bootstrap

### ISSUE THREAD

**Issue by pcanto-hopeit** [iendeavor/vue-next-select#167]
**Feature**
Support customization for adoption look and feel of bootstrap, or may be any other css library. 

**Solution**
Do component withe label

**Comment by gianpaj** [comment]
BTW the CSS can be added in the JS so (I think) it's all concatenated and minified together:
```js
import 'vue-next-select/dist/index.css';
```

**Comment by paulinechi** [comment]
> ```js
> ```js
> import 'vue-next-select/dist/index.css';
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
>       
> ```

Thank you! I was having an issue with CSS and didn't realize that the index.css file needs to be imported
