### ISSUE TITLE
browser hangs/freezes after using the arrow key (down) to scroll through items

### ISSUE THREAD

**Issue by davidhildering** [iendeavor/vue-next-select#168]
browser hangs/freezes after using the arrow key (down) to scroll through items, using chrome browser

1. Go to https://iendeavor.github.io/vue-next-select/
2. Scroll down to 'custom template' (with the bird images)
3. use the arrow down key to scroll
4. browser hangs after two hits

**Expected behavior**
browser should not hang/freeze

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

I'm facing the problem in my own app, but I noticed it was also happening in the demo page with the birds.

**Comment by iendeavor** [comment]
I cannot reproduce this bug in my MacBook. 😞

**Comment by wolfjagger** [comment]
I just saw this on linux/firefox. Maybe it's something with stickiness? I can reliably reproduce it by:

Start the webpage below the select box, e.g. open https://iendeavor.github.io/vue-next-select/#props.
Scroll up to the box, click on it.
Down arrow twice.

**Comment by mttzzz** [comment]
saw this at winddow 10 + chrome latest. But now i cant reproduce.

**Comment by iendeavor** [comment]
I guess it is due to infinite loop, I added safe count to prevent it.

Hope 69b3ff0 fix this issue.

If it is not, please re-open this issue.

**Comment by liborzahradka** [comment]
> I guess it is due to infinite loop, I added safe count to prevent it.
> 
> Hope [69b3ff0](https://github.com/iendeavor/vue-next-select/commit/69b3ff0df9a3208d97feca0590d7e2289c685aca) fix this issue.
> 
> If it is not, please re-open this issue.

Works, tested on Windows 10
- Chrome v90.0.4430.212
- Edge v90.0.818.66
- FF v88.0
