### ISSUE TITLE
Searchable is to exact

### ISSUE THREAD

**Issue by MatthijsBe** [iendeavor/vue-next-select#169]
I stumble on a problem with the searchable setting, when this is turned on I can search though the available options, but when an option has a character with a accent e.g. (é, ë, á, ä) this won't show up and you need to add the accent to the e to get the results you want. 

**Describe the solution you'd like**
It should be nice if this is included inside the code of searchable so when you type a letter without the accent options with accents do show up.

**Describe alternatives you've considered**
For now I need to find a way to do this with  @search:input and  @search:change

**Comment by iendeavor** [comment]
You could use `:visible-options` and `@search-input` to achieve this behavior:

Dynamically change `:visible-options` when `@search-input` event emits.

For related examples: check [here](https://iendeavor.github.io/vue-next-select/#asynchronous-select-header).

**Comment by iendeavor** [comment]
Internally, in addition, we use strict equality to distinguish options of `:options` and `:visible-options`, if your option is an object, you should carefully keep its **identity**:

```javascript
let a = {}
let b = a
let c = {}
console.log(a === b) // true
console.log(a === c) // false
```

**Comment by MatthijsBe** [comment]
Thanks :)  will look into it :)
