### ISSUE TITLE
Searchable, text you typed is put as value when you select option

### ISSUE THREAD

**Issue by MatthijsBe** [iendeavor/vue-next-select#170]
**Describe the bug**
When searchable is turned on, and you type for example "ca" and select the option "cars" ca is put as value in the select. 
this looks like to be the model value of the input. But when you change the "modelvalue" attribute on the input using `@selected` the value stays "ca"

![image](https://user-images.githubusercontent.com/31308832/115348231-a89c5380-a1b2-11eb-81e9-67733af2a3ff.png)

![image](https://user-images.githubusercontent.com/31308832/115348267-b3ef7f00-a1b2-11eb-8bff-6d026510284c.png)

OR is it something i'm doing wrong and do I need to change something else to see the selected option value inside the input?

**Comment by iendeavor** [comment]
You could use `:clear-on-select="true"` to clear/reset input when you select or remove an option.

Hope this could solve it in your scenario.

**Comment by MatthijsBe** [comment]
Thanks that worked :)
