### ISSUE TITLE
teleport warning

### ISSUE THREAD

**Issue by oliverpool** [iendeavor/vue-next-select#180]
https://github.com/iendeavor/vue-next-select/commit/8e6aee177eae0fab45f1ae6cbbc82f74847e8d01 indroduced the usage of teleport

I see now a warning in the console:
```
Failed to locate Teleport target ...
```

It seems that teleport is intended to be connected to HTML-tags existing outside of the Vue app:
https://github.com/vuejs/vue-next/issues/1705

Why do you use `teleport` in this context? Might a `slot` be enough?

**Comment by iendeavor** [comment]
Since there is lot of duplicated code, I just want to reduce code base size. But it is wrong way to use teleport 😞 . I would fix it soon.

**Comment by oliverpool** [comment]
Thank you so much for the quick fix :+1:
