### ISSUE TITLE
[2.4.1] The dropdown doesn't automatically scroll to the selected item on page load when you open it

### ISSUE THREAD

**Issue by renszee** [iendeavor/vue-next-select#206]
**Describe the bug**
The dropdown doesn't automatically scroll to the selected item on page load when you open it.

**To Reproduce**
Go to https://codesandbox.io/s/wonderful-snowflake-ywwzb?file=/src/App.vue
Click on the select.

**Expected behavior**
The dropdown should be scrolled to the selected item "Netherlands".

**Comment by iendeavor** [comment]
Thanks you for the feedback.

At first glance, I think this is a feature request.
But after some investigation, I noticed that this is a common (or required) behavior in html select on the browser and is also implemented in other list-box/combo-box components, so I changed it back to the bug issue.
