### ISSUE TITLE
how to use this package on options api - vue.js 3 JS not typescript

### ISSUE THREAD

**Issue by bhojkamal** [iendeavor/vue-next-select#233]
Hello,
I am sorry if it is wrong to post here.  
I want to use this package in my application and I am using options api vue.js 3 and only JavaScript not Type script, so I don't need defineComponent too.  I want to filter the options list by typing on select like search. I've gone through the documentation, I tried, still it is not working. I have set up the on main.js/app.js as on document. But on document I have not found for options api - javascript, I am not using typescript.  

Below is my code, which is working without select and search. I want to select/search/filter the options like other we see. I have used bootstap jquery before, it was really easy integrate on application. 

HTML code on template is - 
```
<label class="col-lg-2 my-1 col-form-label" for="hospital_id">Select Hospital: </label>
<select class="form-control" v-model="patient.hospital_id" name="hospital_id" required >
    <option value="" selected>Select Hospital</option>
    <option v-for="hos in hospitals" :key="hos.id" :value="hos.id">{{ hos.name }}</option>
</select>
```

Vue Js code is - 
```
<script>
export default {
  data() {
      return {
          patient: {
            hospital_id:'',
          },
          hospitals:{},
      }
  },
  created() { 
      this.$axios.get('/sanctum/csrf-cookie').then(response => {
        this.$axios.get('/api/users/getHospital')
            .then(response => {
                this.hospitals = response.data;
                // console.log(this.hospitals)
            })
            .catch(function (error) {
                console.error(error);
            });
        })
    },
  methods: {
    addTelePatient() {
        this.$axios.get('/sanctum/csrf-cookie').then(response => {
          this.$axios.post('/api/tele-patients', {patient:this.patient})
            .then(response => {
                console.log(response.data)
                this.$router.push({name: 'telePatients'})
            })
            .catch(function (error) {
                console.error(error);
                alert(error.message)
            });
        })
    }
  },
  beforeRouteEnter(to, from, next) {
      if (!window.Laravel.isLoggedin) {
          window.location.href = "/admin/login";
      }
      next();
  }
}

</script>
```

**Comment by iendeavor** [comment]
@bhojkamal 

>  I want to filter the options list by typing on select like search.

In this case, you can pass [searchable](https://iendeavor.github.io/vue-next-select/api-reference.html#searchable) prop.

By default, it filter labels and ignore cases, you may also use [visible-options](https://iendeavor.github.io/vue-next-select/api-reference.html#visible-options) prop and [search-input](https://iendeavor.github.io/vue-next-select/api-reference.html#search-input) event to customize its behavior.

Full example can be found [here](https://codesandbox.io/s/github/iendeavor/vue-next-select/tree/develop/examples?from-embed=&file=/src/views/RemoteSearching.vue)

---

> HTML code on template is -
> ```
> <label class="col-lg-2 my-1 col-form-label" for="hospital_id">Select Hospital: </label>
> <select class="form-control" v-model="patient.hospital_id" name="hospital_id" required >
>     <option value="" selected>Select Hospital</option>
>     <option v-for="hos in hospitals" :key="hos.id" :value="hos.id">{{ hos.name }}</option>
> </select>
> ```

I have updated the usage for the `options` prop in the [docs](https://iendeavor.github.io/vue-next-select/#options).

---

> I am using options api vue.js 3 and only JavaScript not Type script, so I don't need defineComponent too.

Some IDEs (e.g., [VSCode](https://github.com/microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio)) provides typescript intelligent for `.js` files too, you can find more details on the [vue official description](https://v3.vuejs.org/api/global-api.html#definecomponent).
