### ISSUE TITLE
Adding typescript declartion file

### ISSUE THREAD

**Issue by albertlast** [iendeavor/vue-next-select#291]
**Is your feature request related to a problem? Please describe.**
I would like to use vue-next-select in vuejs 3.2 project in a script tag in lang typescript

```js
<script lang="ts">
import { computed, ref } from "vue";
import VueNextSelect from "vue-next-select";
...
</script>
```

But when i do so i get the error:
![grafik](https://user-images.githubusercontent.com/1782906/131248191-619744e3-7d74-426e-87ff-9dbbc414c256.png)

**Describe the solution you'd like**
So dunno if it a bug or feature request,
but i would like to hav a declaration file for the module vue-next-select.

**Comment by iendeavor** [comment]
Hi @albertlast 👋  

Thank you for opening an issue.

TypeScript is supported in vue-next-select@^2.10.1. 🍾 

Closing this for now but feel free to comment/reopen with additional questions/feedback 😄  .
