### ISSUE TITLE
Bug with value (TypeError: number is not iterable)

### ISSUE THREAD

**Issue by EgorFront** [iendeavor/vue-next-select#347]
**Describe the bug**
Bug with the plugin, with a certain set of options

**To Reproduce**
A reproduce link:
https://codesandbox.io/s/adoring-grass-xi7de?file=/src/views/BasicUsage.vue

1. Go to Basic Usage view
2. Change disabled in one of the option to **true**
3. Reload

**Expected behavior**
No critical errors

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 96

**Additional context**
Its unusual behaivor, but it bug happen only when:
1. value-by="value"
2. disabled: true in one of the option
3. if value is String, bug doesnt happen
4. if value-by is different from "value", all is ok, there is no bug

**Comment by EgorFront** [comment]
was it fixed?

**Comment by iendeavor** [comment]
@EgorFront 

Yes, released in [2.10.2](https://github.com/iendeavor/vue-next-select/blob/main/CHANGELOG.md#2102-2021-11-17)
