### ISSUE TITLE
Pre-select option based in v-model

### ISSUE THREAD

**Issue by AldsTan** [iendeavor/vue-next-select#390]
Firstly, great component, easy to integrate and gets the job done.

Issue:
I am using this as an item selector for an invoicing web app, and would like to be able to edit the invoice, and load the saved items. However, I am unable to pre-select the saved item with this component, and I can't find my case in the documentation.

**Comment by iendeavor** [comment]
@AldsTan 

This seems due to `vue-next-select` will remove invalid option.

For more info please refer to [this discussion](https://github.com/iendeavor/vue-next-select/discussions/227#discussioncomment-897848).

Close this now, if you still encounter this problem, feel free to reopen this 😄.
