### ISSUE TITLE
Examples not available on codesandbox

### ISSUE THREAD

**Issue by HaloElite** [iendeavor/vue-next-select#411]
**Describe the bug**
An error occurs when entering the examples on codesandbox.io.
```
Container Error
Error fetching sandbox.
```

**To Reproduce**
Link to Codesandbox
[Sandbox of Vue-Next-Select](https://codesandbox.io/s/github/iendeavor/vue-next-select/tree/develop/examples?from-embed=&file=/package.json)

**Additional context**
Just as a hint cause it might prevent people from using vue-next-select even tho it's just awesome.

**Comment by iendeavor** [comment]
Thanks you for your feedback 😄 .

Fixed in https://github.com/iendeavor/vue-next-select/commit/15c736621a27d95461aae20c47582dc41dbc398c .
