### ISSUE TITLE
Cannot show the pre-selected value for the select box.

### ISSUE THREAD

**Issue by Dekari** [iendeavor/vue-next-select#445]
**Describe the bug** A clear and concise description of what the bug is.

I have 2 tables.

1st holds all the categories 
2nd holds my settings with 3 fields connected to the category_id.

I have 3 vue-next-select boxes that are using the values from DB (1st to fill in all the options, 2nd to determine what's the selected value each time)

My issue is that on initialization the "Selected" value is not there. 

How should I set up my vue-next-select instances to work with?

The value that they should get pre-selected is:
"v-model="store_cats.store_cat1""  (for 1st select box for example)

**To Reproduce** A reproduce link:
https://codesandbox.io/s/github/iendeavor/vue-next-select/tree/develop/examples?file=/src/views/Playground.vue

**Expected behavior** A clear and concise description of what you expected to happen.

Select box to have the pre-selected options bound from DB.

**Screenshots** If applicable, add screenshots to help explain your problem.

See my full component code:
`<template>

    <div class="card card-style">

        <form action="javascript:void(0)" method="post">

            <div class="content mb-0">
                <h4>Bargain settings</h4>
                <p>
                    Setup limits around bargains in your store.
                </p>
                <div class="row">
                    <div class="col-6">
                        <div class="mx-auto">
                            <div class="float-start">
                                <h6>Store Limit</h6>
                            </div>
                            <div class="stepper rounded-s float-start">
                                <a @click="red_store_limit()"><i class="fa fa-minus color-red-dark"></i></a>
                                    <input type="number" ref="number" min="1" max="99" id="store_limit" name="store_limit" v-model="bargain_settings.store_limit">
                                <a @click="incr_store_limit()"><i class="fa fa-plus color-green-dark"></i></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mx-auto">
                            <div class="mx-auto float-end">
                                <h6>Bargain Limit</h6>
                            </div>
                            <div class="stepper rounded-s float-end">
                                <a @click="red_bargain_limit()"><i class="fa fa-minus color-red-dark"></i></a>
                                    <input type="number" ref="number" min="1" max="99" id="bargain_limit" name="bargain_limit" v-model="bargain_settings.bargain_limit">
                                <a @click="incr_bargain_limit()"><i class="fa fa-plus color-green-dark"></i></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>

                <a href="#" @click="updBargain" :disabled="processing"  class="btn btn-m btn-full rounded-sm shadow-l bg-green-dark text-uppercase font-900 mt-4">{{ processing ? "Please wait" : "Update" }}</a>
                <br/>

            </div>
        </form>
    </div>                          

    <div class="card card-style">

        <form action="javascript:void(0)" method="post">

            <div class="content mb-0">
                <h4>Store settings</h4>
                <p>
                    Setup your store details.
                </p>

                <div class="input-style input-style-always-active has-borders no-icon mb-4">
                    <textarea id="store_descr" name="store_descr" v-model="store_settings.store_descr" placeholder=""></textarea>
                    <label for="store_descr" class="color-highlight">Store small description</label>
                    <em class="mt-n3">(required)</em>
                </div>

                <div class="input-style input-style-always-active has-borders no-icon mb-4">
                    <textarea id="oper_details" name="oper_details" v-model="store_settings.oper_details" placeholder=""></textarea>
                    <label for="store_descr" class="color-highlight">Store operation details</label>
                    <em class="mt-n3">(required)</em>
                </div>

                <a href="#" @click="updStoreDetails" :disabled="processing"  class="btn btn-m btn-full rounded-sm shadow-l bg-green-dark text-uppercase font-900 mt-4">{{ processing ? "Please wait" : "Update" }}</a>
                <br/>

            </div>
        </form>
    </div> 

    <div class="card card-style">

        <form action="javascript:void(0)" method="post">

            <div class="content mb-0">
                <h4>Store Categories</h4>
                <p>
                    Select up to 3 categories for your store.
                </p>

                <div class="row">
                    <div class="col">
                        <label for="store_cat1" class="color-highlight">Store Category 1</label>   
                        <vue-next-select
                        v-model="store_cats.store_cat1"
                        :options="avail_store_cats"
                        label-by="description"
                       value-by="store_cat_id"
                        close-on-select
                        :min="1"
                        class="max-size mt-1"
                    ></vue-next-select>
                    </div>
                </div>                    

                <div class="row">
                    <div class="col">
                        <label for="store_cat1" class="color-highlight">Store Category 2</label>   
                        <vue-next-select
                        v-model="store_cats.store_cat2"
                        :options="avail_store_cats"
                        label-by="description"
                        value-by="store_cat_id"
                        close-on-select
                        :min="1"
                        class="max-size mt-1"
                    ></vue-next-select>
                    </div>
                </div>                    

                <div class="row">
                    <div class="col">
                        <label for="store_cat1" class="color-highlight">Store Category 3</label>   
                        <vue-next-select
                        v-model="store_cats.store_cat3"
                        :options="avail_store_cats"
                        label-by="description"
                        value-by="store_cat_id"
                        close-on-select
                        :min="1"
                        class="max-size mt-1"
                    ></vue-next-select>
                    </div>
                </div>                    

                <a href="#" @click="updStoreCats" :disabled="processing"  class="btn btn-m btn-full rounded-sm shadow-l bg-green-dark text-uppercase font-900 mt-4">{{ processing ? "Please wait" : "Update" }}</a>
                <br/>
            </div>
        </form>
    </div>        
</template>`

Then the script part:
`  import { mapActions } from 'vuex'
    import VueNextSelect from 'vue-next-select'
    import 'vue-next-select/dist/index.min.css'

    export default {
        name:'settings',
        components: {
            'vue-next-select' : VueNextSelect,
        },
        data(){
            return {
                bargain_settings:{
                    user_id: this.$store.state.auth.user.id,
                    store_limit:this.$store.state.auth.user.store.store_limit,
                    bargain_limit:this.$store.state.auth.user.store.bargain_limit
                },
                store_settings:{
                    user_id: this.$store.state.auth.user.id,
                    store_descr:this.$store.state.auth.user.store.store_descr,
                    oper_details:this.$store.state.auth.user.store.oper_details,
                },
                store_cats:{
                    store_cat1:this.$store.state.auth.user.store.cat1_id,
                    store_cat2:this.$store.state.auth.user.store.cat2_id,
                    store_cat3:this.$store.state.auth.user.store.cat3_id,
                },
                avail_store_cats:[],                
                processing:false
            }
        },
        created(){
            this.getAvailStoreCats()
        },     
        methods:{
            ...mapActions({
                signIn:'auth/getUser'
                
            }),
            incr_bargain_limit(field) {
                this.bargain_settings.bargain_limit += 1
            },
            red_bargain_limit() {
                this.bargain_settings.bargain_limit -= 1
            },
            incr_store_limit() {
                this.bargain_settings.store_limit += 1
            },
            red_store_limit() {
                this.bargain_settings.store_limit -= 1
            },                        
            async updBargain(){
                this.processing = true
                await axios.post('/api/updstore_limits',this.bargain_settings).then(({data}) => {

                    if (!data.success) {
                        this.do_show_popup_error(data.message)
                    } else {
                        this.do_show_popup_success(data.message)
                        this.signIn() // refresh local data
                    }
                }).catch(({response:{data}})=>{
                    this.do_show_popup_error(data.message)
                }).finally(()=>{
                    this.processing = false
                })
            },
            async updStoreDetails(){
                this.processing = true
                await axios.post('/api/updstore_settings',this.store_settings).then(({data}) => {

                    if (!data.success) {
                        this.do_show_popup_error(data.message)
                    } else {
                        this.do_show_popup_success(data.message)
                        this.signIn() // refresh local data
                    }
                }).catch(({response:{data}})=>{
                    this.do_show_popup_error(data.message)
                }).finally(()=>{
                    this.processing = false
                })
            },
            async updStoreCats() {
                this.processing = true
                await axios.post('/api/updstore_cats',this.store_cats).then(({data}) => {

                    if (!data.success) {
                        this.do_show_popup_error(data.message)
                    } else {
                        this.do_show_popup_success(data.message)
                        this.signIn() // refresh local data
                    }
                }).catch(({response:{data}})=>{
                    this.do_show_popup_error(data.message)
                }).finally(()=>{
                    this.processing = false
                })
            },
            async getAvailStoreCats(){
                this.processing = true
                await axios.get('/api/get_avail_store_cats').then(({data}) => {

                    if (!data.success) {
                    } else {
                        this.avail_store_cats = data.avail_store_cats
                    }
                }).catch(({response:{data}})=>{
                    this.do_show_popup_error(data.message)
                }).finally(()=>{
                    this.processing = false
                })
            }
        }
    }`

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by may-96** [comment]
Did you find any solution? I'm facing the exactly same issue

**Comment by iendeavor** [comment]
Please refer to this discussion: https://github.com/iendeavor/vue-next-select/discussions/227#discussioncomment-897848
