### ISSUE TITLE
using creatable with taggable the search field goes down

### ISSUE THREAD

**Issue by bci24** [iendeavor/vue-next-select#47]
I think there is an issue here using this example: https://iendeavor.github.io/vue-next-select/#creatable-header

I attached some captures with the issue.

If using taggable the input with the search field is not "replacing" the select, the input with "Type to search" is going down (under  "Select option"). 

If you not using taggable and you click "select option" the field is "replaced" with "Type to search" which is supposed to do if using taggable too.

Is this a bug or this is supposed to work if using taggable ?

![Screenshot from 2020-12-09 15-14-23-min](https://user-images.githubusercontent.com/49674076/101634854-ec779300-3a31-11eb-9dde-7a17b13fc303.png)
![Screenshot from 2020-12-09 15-14-48-min](https://user-images.githubusercontent.com/49674076/101634858-ec779300-3a31-11eb-8b99-499747915a82.png)
![Screenshot from 2020-12-09 15-15-31-min](https://user-images.githubusercontent.com/49674076/101634859-ed102980-3a31-11eb-99f9-6196558ca20d.png)
![Screenshot from 2020-12-09 15-15-59-min](https://user-images.githubusercontent.com/49674076/101634860-ed102980-3a31-11eb-8f10-76f89f300c8e.png)
![Screenshot from 2020-12-09 15-16-16-min](https://user-images.githubusercontent.com/49674076/101634861-eda8c000-3a31-11eb-8e87-41b6b8a02bab.png)

**Comment by iendeavor** [comment]
@bci24 I personally think that it is not a bug.

A full usage of multiple/searchable/taggable/creatable can be found in https://codesandbox.io/s/vue-next-select-example-for-taggablesearchablecreatable-hub6y?file=/src/App.vue.
