### ISSUE TITLE
是否可禁用 option toggle

### ISSUE THREAD

**Issue by Wujidadi** [iendeavor/vue-next-select#62]
您好！正在尋找 Vue 3.x 的 select 方案時看到這個專案，great work! The single-page documentation is also excellent!

想請教一下：Single select，若重複點選同一個 option，會有 toggle 的效果，這似乎與一般 html 的 select 效果有所差異，可能也和一般使用者期待的體驗不同。是否考慮在 props 中增加此開關（目前我在 props 中並未發現……）？

本來 issue 要用英文寫的，看到閣下同樣來自台灣，有點高興！請容許我用中文表達（可能比較順）……

**Comment by iendeavor** [comment]
嗨~

> 若重複點選同一個 option，會有 toggle 的效果

請問這邊指的是說：「在被選取的狀態下，點擊該選項不應取消掉該選項」嗎?
如果是，可以使用 `:min="1"` 來達成此效果哦

**Comment by Wujidadi** [comment]
Yes! 就是這個意思～～～
原來 `min` 和 `max` 屬性是這個效用，看來我之前誤會了……
謝謝您的指教！

**Comment by iendeavor** [comment]
若有其他需求，也歡迎再提出~
